# settings
set-option -g default-terminal "screen-256color"
set-option -g terminal-overrides ',xterm-256color:RGB'
set-option -g default-shell $SHELL
set-option -g automatic-rename off
set-option -g allow-rename off
set-option -g window-status-format "#I: #W"
set-option -g window-status-current-format "#I: #W"
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set -g mouse on                  # Activate mouse mode
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# binding

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix

# set v to vim copy-mode
bind 'v' copy-mode

# tab splitting
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# skip confirmation when closing a pane
unbind x
bind x kill-pane

# rebind closing of windows and skip confirmation
unbind '&'
bind X kill-window

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

unbind 'k'
bind-key "k" run-shell "sesh connect \"$(
  sesh list -tz --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^f configs ^t sessions ^x zoxide ^d tmux kill' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-f:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list -zt --icons)' \
    --bind 'ctrl-r:execute(tmux rename-session -t {2..} {q})+change-prompt(⚡  )+reload(sesh list -zt --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""


# Plugins 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'sainnhe/tmux-fzf'

run '~/.config/tmux/plugins/tmux/catppuccin.tmux'

# Plugin settings
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @catppuccin_flavour 'mocha' # or frappe, latte, mochh}"
set -g @catppuccin_date_time_text "%H:%M"a

# Set the Catppuccin flavor (options: latte, frappe, macchiato, mocha)
set -g @catppuccin_flavor "mocha"

# Window options
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_status_style "basic"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"

run '~/.tmux/plugins/tpm/tpm'
