
# This is the main config, and is only used to source the configs

source = $HOME/.config/hypr/modules/monitors.conf
source = $HOME/.config/hypr/modules/autostart.conf
source = $HOME/.config/hypr/modules/environment.conf
source = $HOME/.config/hypr/modules/styling.conf
source = $HOME/.config/hypr/modules/input.conf
source = $HOME/.config/hypr/modules/keybinds.conf
source = $HOME/.config/hypr/modules/win_workspace.conf
source = $HOME/.config/hypr/modules/animations/animations.conf


# Attempts to optimze: 

# These are set according to https://wiki.hypr.land/Configuring/Performance/
decoration:blur:enabled = false
decoration:shadow:enabled = false
misc:vfr = true
