
# External monitor (left of internal)
# monitor=HDMI-A-1, 2560x1440@144, -2560x0, 1
monitor=HDMI-A-1, 2560x1440@60, auto, 1

# Internal laptop display
# monitor=eDP-1, 2560x1600@60, 0x0, 1.33
# monitor=eDP-1, 2560x1600@60, 0x0, 1.6

#monitor=eDP-1, 2560x1600@60, 0x0, 1
#monitor=eDP-1, 2560x1600@144, 0x0, 1
monitor=eDP-1, 2560x1600@240, 0x0, 1.6
#monitor=eDP-1, 2560x1600@60, 0x0, 1.6
monitor=DP-1, highres@highrr, auto, 1.25

# Should remove blurryness
xwayland {
  force_zero_scaling = true
}

workspace=1, monitor:DP-1
workspace=2, monitor:DP-1
workspace=3, monitor:DP-1
workspace=4, monitor:DP-1
workspace=5, monitor:DP-1

workspace=6, monitor:eDP-1
workspace=7, monitor:eDP-1
workspace=8, monitor:eDP-1
workspace=9, monitor:eDP-1
workspace=10, monitor:eDP-1

