# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$
windowrule = float,class:^(waypaper)$

windowrule = float,class:^(yazi-float)$
windowrule = center, class:^yazi-float$
windowrule = size 1000 700, class:^yazi-float$


windowrule = float,class:^(zephyrusctl-float)$
windowrule = center, class:^zephyrusctl-float$
windowrule = size 1000 700, class:^zephyrusctl-float$

# Files (file manager) floating configuration
windowrule = float,class:^(org.gnome.Nautilus)$
windowrule = center,class:^(org.gnome.Nautilus)$
windowrule = size 1000 700,class:^(org.gnome.Nautilus)$

# Blueberry (Bluetooth manager) floating configuration
windowrule = float,class:^(blueberry.py)$
windowrule = center,class:^(blueberry.py)$
windowrule = size 800 600,class:^(blueberry.py)$

# PulseAudio Volume Control floating configuration
windowrule = float,class:^(org.pulseaudio.pavucontrol)$
windowrule = center,class:^(org.pulseaudio.pavucontrol)$
windowrule = size 800 600,class:^(org.pulseaudio.pavucontrol)$

# GNOME Calculator floating configuration
windowrule = float,class:^(org.gnome.Calculator)$
windowrule = center,class:^(org.gnome.Calculator)$
windowrule = size 400 500,class:^(org.gnome.Calculator)$

# Window placement rules
# windowrulev2 = workspace 1, class:^(firefox)$
# windowrulev2 = workspace 2, class:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
